version: '3.8'
services:
  mongo:
    image: mongo:7
    container_name: momentic-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["--bind_ip_all"]
  redis:
    image: redis:7-alpine
    container_name: summary-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

volumes:
  mongo_data:
    driver: local
  # Redis uses ephemeral storage by default; add a volume if persistence is desired
